### ISSUE TITLE
Multiple Cognito Callback URLs and signed out URLs? 

### ISSUE THREAD

**Issue by hyphen1370** [aws-samples/cloudfront-authorization-at-edge#135]
Hello, 

For this app, is that possible to handle multiple callback URL? 

After I deployed the app with option 1 and all the default options, I would like to add more callback and signed-out URLs into the app client settings? 

Here is what I did: 

1. Go to the CloudFront distribution and add the cnames like test.example.com
2. Add to DNS to make sure cname record exist
2. Go to Cognito pool is created, add https://test.example.com/parseauth after the default CloudFront URL for callback URL text field
3. add https://test.example.com/ after the default CloudFront URL for signed out url. 

When I go to https://test.example.com and login, it redirects me back to the default CloudFront URL instead of https://test.example.com. So, is there anything to make the following work? 

When I go to https://test.example.com and login, redirect me to https://test.example.com
When I go to the default CloudFront URL and login, redirect me to the default CloudFront URL

Thanks

**Comment by ottokruse** [comment]
Hi @hyphen1370 . Not sure why it is not working for you but it "should" work as you want, because the code that generates the redirect URL uses the current domain name (from the HTTP "Host" header):

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/874959a11dedd6edd75164056a934dbd504ba016/src/lambda-edge/check-auth/index.ts#L116

To gather more info, if you set log level to debug and verify the logs of the checkAuth Lambda function, you can see what the input event looked like, e.g. what the Host header was?

**Comment by hyphen1370** [comment]
Thanks. I figured out
