### ISSUE TITLE
CloudFormation stack creation fails when I try to use an existing Cognito User Pool and App client

### ISSUE THREAD

**Issue by chris-denglere** [aws-samples/cloudfront-authorization-at-edge#144]
I'm trying to get the stack to work with an existing Cognito user pool and app client. I'm specifying the correct parameters in the template.

The stack creation fails when the User Pool Client Update Handler throws an exception. 

Here's the stack trace:

`ERROR	InvalidParameterException: Invalid range for token validity.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidParameterException',`

Any ideas what might be causing this?

**Comment by ottokruse** [comment]
Seems to be the Cognito token expiry settings on the client. But the stack doesn't explicitly set or alter those, what is their current existing value?

In the logs should also be the contents of the [update API call](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/43c1a48d9f04bc2b4e058e644eae7ee54d97f121/src/cfn-custom-resources/user-pool-client/index.ts#L89), anything funky in there? Might debug this by trying to do the same update from the command line using AWS CLI, and mess around a bit to figure it out.

**Comment by chris-denglere** [comment]
Refresh, access, and ID tokens are all set to 120 minutes. Console says the ID and access tokens can't be greater than the the refresh token expiry, which makes sense. But is there a disconnect between the UI and the backend with respect to the expiration settings? I guess I'll try updating from the CLI to figure that part out.

I looked at the update API call, everything looks fine there.

Thanks for the pointers so far.

**Comment by ottokruse** [comment]
Closing for now, let me know if there's still any issue.

**Comment by james1050** [comment]
I've also run into this error today when importing the packaged SAM template for this repo into my own CDK stack. Previously I've not run into this issue using the standalone deployment instructions in the README, even using existing UserPool + UserPoolClient. 

I noticed a discrepancy between my new CDK generated UserPoolClient and my old UserPoolClient. It had 'Enable Token Revocation' checked. Tried unchecking this through the AWS console and redeploying. No longer ran into this error. Not sure how it's relevant, maybe the act of editing the client in the console itself fixed the problem. 

@ottokruse I agree that the error sounds like it's related to setting an incorrect token param in [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#updateUserPoolClient-property) call but I don't understand how because the user-pool-client handler doesn't specify any token related params. Perhaps a work around would be to create the `cognitoClient.updateUserPoolClient(input)` input params from all the relevant params in the `existingUserPoolClient` object so all the existing params would be included in the call. That would have been my next attempt to fix the problem.

**Comment by ottokruse** [comment]
> Perhaps a work around would be to create the cognitoClient.updateUserPoolClient(input) input params from all the relevant params in the existingUserPoolClient object so all the existing params would be included in the call.

Gave that a quick shot in #168 and it seems to do the trick. I tested with a pre-existing User Pool Client with 'Enable Token Revocation' checked and customized token expiry times (120 minutes)

**Comment by james1050** [comment]
Thanks Otto and thank you for your great work on this sample. It's very useful.
