### ISSUE TITLE
[Question] Different groups for different S3 origins/behaviors?

### ISSUE THREAD

**Issue by noamross** [aws-samples/cloudfront-authorization-at-edge#175]
Hello! Thank you for this great resource!

I'd like to modify this so my cloudfront distribution points different paths (`/bucket1`, `/bucket2`, `/public`) to different S3 buckets, and make separate groups within the cognito pool, each of which is able to access different buckets.  I think I can create the new behaviors and buckets through the console if needed, but I am unsure what to modify in the lambda functions to implement this. For simplicity I could just use the the paths (`bucket1`) as group names.  Can you direct me at all to how to do this?

**Comment by ottokruse** [comment]
If you want users to enter the path in the URL (/bucket1, /bucket2, /public), then you'd have to add code to the CheckAuth Lambda handler, that checks if the token's group matches with the path, and throw 403 if no match. Also instead of 1 default CloudFront behavior that forwards traffic to S3, you need to have a behavior for each S3 bucket (origin). Attach the checkAuth function to each of these behaviors.

If you want the bucket choice to be transparent to the user, i.e. go to the right bucket automatically based on their group, and users don't need to use a different path in the URL, then use an origin request Lambda@Edge trigger to choose the right origin (s3 bucket). The trick will be to make the group available to that L@E function since it can't access the cookie with the JWT without you configuring CloudFront to forward that cookie to the origin (and the default Amplify compatibility uses cookies with a user dependant dynamic name).

**Comment by ottokruse** [comment]
Let me know if that helps.
Cheers!

**Comment by ottokruse** [comment]
Closing for now
