### ISSUE TITLE
Question: redirecting after download from S3

### ISSUE THREAD

**Issue by dolsysmith** [aws-samples/cloudfront-authorization-at-edge#273]
Thank you for this template -- it works great, and it saved us a lot of time. 

Our use case is a bit different from what you've described, however: we just want to set up SAML authentication so that any users from our organization can download files from an S3 bucket; the users will have direct links to the files via the Cloudfront endpoint, e.g., `https://our-app-id.cloudfront.net/object_folder/an_object.pdf`. As deployed, that part works -- i.e., where the URL matches an object in the S3 bucket, the download happens seamlessly -- but it seems to leave the user's browser tab on the sign-in page, which is potentially confusing. 

Do you know how I might go about modifying the lambda code to redirect after each request, i.e., to a default landing page?

Thanks for any suggestions.

**Comment by ottokruse** [comment]
So the problem is the browser starts downloading the file in the background, but that means it still shows the login page?

Would this work then?

- do not give users direct links to the actual files but instead to a landing page where you pass the filename as query parameter. So eg https://yourdomain.com/download?key=filename.pdf instead of https://yourdomain.com/filename.pdf
- and the landing page then is a simple HTML file with a line of text "download started" and a line of JavaScript that sets window.location.hostname to the filename from the query parameters ("key" in my example), which redirects the browser to that file client side. 

I don't think you can escape from having a landing page like that, the browser will have to show something after the login page.

**Comment by dolsysmith** [comment]
Thank you! That seems like a straightforward solution; I really appreciate the help.
