### ISSUE TITLE
[Question]Signing out doesn't work

### ISSUE THREAD

**Issue by KakeruSakai** [aws-samples/cloudfront-authorization-at-edge#284]
Hello, I have a question about signing out.

Problem: I want to add a signout button to the website and sign out with /signout, but the authentication information stored in the cookie is not completely discarded.

When cognito authentication is completed, the following authentication information is stored in the cookie with the following keys:

・accessToken
・refreshToken
・idToken
・tokenScopesString
・userData
・LastAuthUser
・amplify-signin-with-hostedUI
When you actually sign out,

・refreshToken
・accessToken
・spa-auth-edge-pkce
・spa-auth-edge-nonce-hmac
・spa-auth-edge-nonce

are stored in the cookie.

Other information:

・It works fine if you do it with the browser validator open.

・If you do it without the validator open and look at the validator console after doing it, you will see a warning that says "Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation." ←Due to browser specifications, is it not possible to completely discard (expire) the cookie contents by using /signout?

If you know anything about this, I would appreciate it if you could let me know.
Thank you in advance.

**Comment by ottokruse** [comment]
Hi mate.

Q1: What version of Auth@Edge are you on?
Q2: What cookie settings are you using? Do you use a different setting for the ID token?
Q3: How do you trigger sign out? Via Amplify or via navigating to the signout URL?

The cookie expiry code is here: https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/2d1143c9413c339b690d544895920aa264a39ccc/src/lambda-edge/shared/shared.ts#L446

Sign out should expire all those cookies.

> "Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation." 

Auth@Edge does not use 3rd party cookies so that message shouldn't be related

**Comment by KakeruSakai** [comment]
Thank you for your reply.
Q1: The version is 2.21.
Q2: The cookie settings are the default, and the parameter settings at the time of deployment are as follows.
CookieCompatibility:amplify,
CookieSettings:{ "idToken": null, "accessToken": null, "refreshToken": null, "nonce": null },
AdditionalCookies: {}
Q3: The sign-out URL is used as the trigger. For example, the link is "https://example.cloudfront.net/signout".

I'm sorry to bother you during your busy schedule, but I would appreciate your help.

**Comment by ottokruse** [comment]
It may help to first go to 2.3.0 -- there were some changes in #271 that may have a positive impact.

Then let's try this again. It *should* work. When cookie expiry doesn't work it's usually because the cookiesettings mismatch (cookies were set with a different path). To verify this pay close attention to the Cookie header is it comes back from Auth@edge initially (after sign in) and then after signout and spot any differences. The signout headers should be the same, just have an empty value and the maxAge and expire keys

**Comment by KakeruSakai** [comment]
Thank you.
After /signout, if I refresh the browser, I'm redirected to the hosted UI, is this normal?

**Comment by ottokruse** [comment]
Yes. Signing out should bring you to the Hosted UI (shouldn't need refresh, unless your browser cached the page locally)

**Comment by KakeruSakai** [comment]
Thanks, worked fine!!
