### ISSUE TITLE
Serverless Application not available in SAR

### ISSUE THREAD

**Issue by nickmccarthy-grainbridge** [aws-samples/cloudfront-authorization-at-edge#31]
Is this application no longer published in the SAR?

I have tested from multiple accounts using administrative roles (with access to serverlessrepo), and am unable to access the application as specified in the README: `spa-authorization-at-edge`, nor the application specified in the `reuse-auth-only.yaml` template `cloudfront-lambda-edge-cognito-auth`

`An error occurred (AccessDeniedException) when calling the CreateCloudFormationTemplate operation: User: *** is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:520945424137:applications/spa-authorization-at-edge`

`An error occurred (AccessDeniedException) when calling the CreateCloudFormationTemplate operation: User: *** is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-lambda-edge-cognito-auth`

I can follow the process to build myself, but initial deployment and testing would be easier if the SAR application was accessible.

**Comment by nickmccarthy-grainbridge** [comment]
Researching this issue, I see a third application name referenced here:
https://github.com/aws-samples/cloudfront-authorization-at-edge/commit/1d9e9be4c4ae34f8297c772168bd52bdc6aae0d3

arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge
        SemanticVersion: 1.0.6

This version appears to be valid, so documentation and examples may need to be updated to reflect this change.

**Comment by ottokruse** [comment]
Sorry mate there were old links floating around, that used the old name. I have fixed that in #33 .

You are right, that is the right one:

```
arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge
        SemanticVersion: 1.0.6
```

SAR link: https://console.aws.amazon.com/serverlessrepo/home?region=us-east-1#/published-applications/arn:aws:serverlessrepo:us-east-1:520945424137:applications~cloudfront-authorization-at-edge

By the way, we do release updates to the SAR evety now and then. How do you keep track of that, so that you can update your pinned version?

**Comment by ottokruse** [comment]
FYI just released v1.0.7 to the SAR

**Comment by ottokruse** [comment]
Closing this issue for now as I think your issue has been resolved

**Comment by iuliu-b** [comment]
Howdy - sorry to say I'm here because of the same issue. Deploying other things in the SAR works fine, but when I try to follow the README link (https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge) I get the same error as above.

Relatedly(?) when I search the SAR for *"cloudfront-authorization-at-edge"* this app does not come up in the results.

**Comment by ottokruse** [comment]
It's back again @iuliu-b now - thanks for mentioning! It was set to private erroneously
