### ISSUE TITLE
Cannot teardown lambda@edge when using custom distribution

### ISSUE THREAD

**Issue by mneil** [aws-samples/cloudfront-authorization-at-edge#61]
I have a stack that has several lambdas for lambda@edge on a cloudfront distribution. The distribution is in stack A. I've launched this application as stack B and did not use the cloudfront distribution included with it.

I can't delete stack B because stack A references the lambdas in the stack as imports. So I teardown stack A. Now I go to tear down stack B. I can't because the lambdas are replicated for lambda@edge. I get an error when I try to manually delete the lambdas.

An error occurred when deleting your function: Lambda was unable to delete arn:aws:lambda:redion:accountId:function:stack-name-ParseAuthHandler-someid:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.

I read the documentation, it says to go to my distribution (stack A) and delete the lambda. Well, that distribution was already deleted. I can't do that. 

I reached out to support to help me delete these lambdas. I think this is a bug. I know it's probably not possible for you to fix this. So, assuming I'm correct and this is a bug, and that you have no ability to actually prevent this behavior, I'd like to suggest some features and changes.

Feature:
  Output the lambda arns to SSM so I can reference them that way instead of using ImportValue in my own stack. You could do this in addition to the output values.

Request:
  Add a not in the documentation that this can happen and advise users us the SSM parameters and teardown this stack first (my stack B) before attempting to teardown stack A (my cloudfront distro).

**Comment by rpattcorner** [comment]
Truth in advertising ... I'm not an author of this stack, I'm a very minor contributor.  But I use the stack in the way that you do, however without additional lambda@edges in my parent stack.

That said, my experience has been that you can fairly easily locate the ARNs of the lambdas created by the (cloudfront authorization at edge) nested stack in a couple of places:

1. In the lambda console or CLI itself.  For example:
![image](https://user-images.githubusercontent.com/1488518/83905975-aa8f2c80-a730-11ea-8363-ee3217b94384.png)

2. As entries in the cloudwatch event logs

In either case you can delete the remaining lambdas from cli (by ARN) or through the console.  But ... as AWS [points out](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-delete-replicas.html), you can only delete them once all the references to them are gone.

Here my experience diverges from the documentation.  The doc says basically you can delete the hanging lambdas once the last (in our case cloudfront) reference to them is gone, which would mean simply deleting the references in the cloudfront `behaviours` section.  I've found that fails more often than succeeds.  And it wouldn't help you anyway, since your self-created cloudfront died when you deleted the parent stack.

But ... once the references are gone, and they should be now that your parent stack and the cloudfront it created died, you *can* delete the lambdas once the unreferenced edge instances age out.  I've found that takes 6-12 hours, depending on how many regions you deployed in.

So give it a try once you've slept on it.  If that fails, or in the entirely possible event that I've completely misunderstood, you might want to contact AWS support and ask them to look at the edge lambdas that remain and tell you what artifacts are referencing them, so you can delete the blocking references.

But, as I think, the ARNs of the stale edge lambdas from the child stack should be available to you regardless.

**Comment by mneil** [comment]
I did consider that it might take some time. I'll try back again on Monday. For now I've redeployed the stacks which generates different lambda names and and able to use them. I already did create an AWS support ticket as well. Hopefully it clears itself up, as you say. Would still be good to make a note of it just in case. If not here, maybe in the AWS docs. I'll mention that to support :).

**Comment by ottokruse** [comment]
Closing for now as I do not believe there is an action for this repo
