### ISSUE TITLE
[Question] Redirect to localhost for application authentication debugging

### ISSUE THREAD

**Issue by rpattcorner** [aws-samples/cloudfront-authorization-at-edge#70]
@ottokruse 
We're working on the problem of bootstrapping authentication in an SPA.  By bootstrapping I mean supplying the SPA with the basic configuration information it needs to make AWS API calls without having to compile information into the code.  The key piece of configuration information needed is the bucket that the SPA is running in and the cognito identity pool that gives the app its internal role/permissions.

The debug cycle is very difficult, as currently you need to:
1. Recompile the app with debug statements
2. Reupload the complied SPA to S3
3. Invalidate
4. Test
5. Repeat

We have a version of the (node) app that runs locally on 8080 and would like to be able to redirect to the local instance instead of the S3 hosted version  -- and do so **with the entire authentication chain intact** .  That is, since we're examining the results of authentication, we want the entire authorization-at-edge framework to execute as usual, then instead of sending the final redirect call to the index.html in the bucket, sending it to the localhost:8080/index.html url.

From my reading of the blog, the place to do the change in the final destination is the checkConfig handler.  Is that right?

When I inspect the lambda code in the repository there's an easy and obvious place: the checkauth [index.ts ](https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/check-auth/index.ts) line 18:

`    const domainName = request.headers['host'][0].value;`

suggesting that a simple change to set domainName to 'localhost:8080' should do the job.

1. Is this understanding correct?  Is there a better way to accomplish the goal of local debugging with authentication active?
2. I then tried to simply update the lambda version in place.  However when I do so I do not see index.ts, but rather a bundle.js

I'm figuring the bundle is a compressed webpack of index.ts so I thought no problem, as generally a webpack obfuscation just removes spaces and punctuation.  But when I examine bundle.ts the code seems to bear no relationship to checkAuth:index.ts, and in fact does not reference the domainName variable I want to change.

I'd like to avoid forking the entire application, as that would be a whole new toolchain to learn and set up - part of the appeal was consuming an existing app.

Do you have any thoughts on how to modify checkAuth for local debugging (if my approach seems viable in the first place) or how to approach the overall goal?

**Comment by ottokruse** [comment]
Interesting question 👍 

To route traffic to your developer laptop, you need to have it as your CloudFront origin, instead of the S3 bucket. The line of code you refer to just reads the host from the CloudFront event meta data, changing it there won't work (it's meant to be read not altered).

I think an approach that might work is (but is not trivial):

- Setup a throw away EC2/LightSail/Cloud9 environment where you develop and run your web app in development/hot-reload mode
- Make that environment publicly available so CloudFront can route to it (expose port 8080 to public internet. It will have some random URL that people would not guess hopefully - but if you really only want to allow traffic from CloudFront you're going to have to set a secret header in CloudFront, and check that in your dev server)
- Use your EC2/LightSail/Cloud9 environment as origin to CloudFront, instead of the S3 bucket. (that would require you to change the CloudFront distribution after deploying it)

VS Code has great features for remote developing against e.g. an EC2: https://code.visualstudio.com/docs/remote/remote-overview

You could also use your dev laptop instead of EC2/LightSail/Cloud9 but that would be more scary to expose to public internet than a throw away dev environment.

**Comment by rpattcorner** [comment]
That sounds promising, thanks!
